resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: pull-request
  type: pull-request
  source:
    repo: gbgdev/concourse-lab
    access_token: {{github-token}}

jobs:
- name: verify-pull-request
  plan:
  - get: pull-request
    trigger: true
  - put: pull-request
    params: { path: pull-request, status: pending }
  - task: some-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: node, tag: 8-alpine }
      run:
        path: sh
        args:
        - -cx
        - npm test
        - ls -al
    on_success:
      put: pull-request
      params: { path: pull-request, status: success }
    on_failure:
      put: pull-request
      params: { path: pull-request, status: failure }
