---
resources:
- name: repository
  type: git
  source:
    uri: https://github.com/gbgdev/concourse-lab

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: repository
  - task: dummy-task
    file: repository/tasks/dummy-task.yml
