resources:
- name: repository
  type: git
  source:
    uri: git@github.com:gbgdev/concourse-lab.git
    branch: master
    private_key: {{github-private-key}}

- name: release-docker-image
  type: docker-image
  source:
    repository: gbgdev/dummy
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

jobs:
- name: create-release-image
  public: true
  plan:
  - get: repository
  - task: write-version
    file: repository/task_release_version.yml
  - put: release-docker-image
    params:
      build: repository
      tag: tags/git_rev
      tag_as_latest: true
