resources:
- name: repository
  type: git
  source:
    uri: https://github.com/gbgdev/concourse-lab.git
    branch: master

- name: release-docker-image
  type: docker-image
  source:
    repository: gbgdev/dummy
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

jobs:
- name: create-release-image
  public: true
  plan:
  - get: repository
  - put: release-docker-image
    params:
      build: repository
      tag: 1.0
      tag_as_latest: true
