resources:
- name: repository
  type: git
  source:
    uri: https://github.com/gbgdev/concourse-lab.git
    branch: master

- name: release-docker-image
  type: docker-image
  source:
    repository: gbgdev/dummy
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

jobs:
- name: create-release-image
  public: true
  plan:
  - get: repository
  - task: write-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine/git
      inputs:
          - name: repository
      outputs:
          - name: tags
      run:
        dir: repository
        path: sh
        args:
        - -exc
        - |
          git rev-parse --short HEAD > ../tags/git_rev
  - put: release-docker-image
    params:
      build: repository
      tag: tags/git_rev
      tag_as_latest: true
