---
resources:
- name: repository
  type: git
  source:
    uri: https://github.com/gbgdev/concourse-lab.git

jobs:
- name: job-dummy
  public: true
  plan:
  - get: repository
  - task: dummy-task
    file: repository/01_basic_pipeline/tasks/dummy-task.yml
